// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EmpleadosAPI.Models;

public partial class Archivo
{
    public int ArchivoId { get; set; }

    public string Nombre { get; set; }

    public string NombreOriginal { get; set; }

    public long Tamano { get; set; }

    public string ContentType { get; set; }

    public string Ruta { get; set; }
}