// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EmpleadosAPI.Models;

public partial class Empleado
{
    public int EmpleadoId { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int DepartamentoId { get; set; }

    public int PuestoId { get; set; }

    public decimal Salario { get; set; }

    public DateOnly FechaNacimiento { get; set; }

    public DateOnly FechaContratacion { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public string CorreoElectronico { get; set; }

    public int EstadoId { get; set; }

    public string FotografiaRuta { get; set; }

    public virtual Departamento Departamento { get; set; }

    public virtual Estado Estado { get; set; }

    public virtual Puesto Puesto { get; set; }
}